# Part-A

## Question-1

In [2]:
import numpy as np

# a) Check the version of NumPy and create 1D, 2D arrays.
print("NumPy Version: ", np.__version__)

# Create 1D array
array_1d=np.array([1, 2, 3, 4, 5])
print("1D Array: ", array_1d)

# Create 2D array
array_2d=np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

NumPy Version:  1.23.5
1D Array:  [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# b) Check the data type and dimension of created arrays
print("Data Type of 1D array: ", array_1d.dtype)
print("Dimension of 1D array: ", array_1d.ndim)
print("Data Type of 2D array: ", array_2d.dtype)
print("Dimension of 2D array: ", array_2d.ndim)

Data Type of 1D array:  int64
Dimension of 1D array:  1
Data Type of 2D array:  int64
Dimension of 2D array:  2


In [4]:
# c) Find the size of each element in the arrays.
print("Size of each element in 1D array: ", array_1d.itemsize)
print("Size of each element in 2D array: ", array_2d.itemsize)

Size of each element in 1D array:  8
Size of each element in 2D array:  8


In [5]:
# d) Find the number of rows and columns of 2D array.
print("Number of Rows and Columns in 2D array: ", array_2d.shape)

Number of Rows and Columns in 2D array:  (2, 3)


In [6]:
# e) Reshape the array from shape (2, 3) to (3, 2).
reshaped_array=array_2d.reshape((3, 2))
print("Reshaped Array: \n", reshaped_array)

Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]]


## Question-2

In [7]:
# a) Slice the 1D array to get [6, 3, 9]
array_1d_to_slice=np.array([4, 5, 6, 3, 9, 7])
sliced_array_1d=array_1d_to_slice[2:5]
print("Sliced 1D Array: ", sliced_array_1d)

Sliced 1D Array:  [6 3 9]


In [8]:
# b) Slice the 2D array to get [[1, 2]].
array_2d_to_slice=np.array([[1, 2, 3], [4, 5, 6]])
sliced_array_2d=array_2d_to_slice[0:1, 0:2]
print("Sliced 2D Array: \n", sliced_array_2d)

Sliced 2D Array: 
 [[1 2]]


## Question-3

In [9]:
# a) Concatenate two 1D arrays [4,5,6,7] and [3,4,1].
array_1=np.array([4, 5, 6, 7])
array_2=np.array([3, 4, 1])
concatenated_array_1d=np.concatenate((array_1, array_2))
print("Concatenated 1D Array: ", concatenated_array_1d)

Concatenated 1D Array:  [4 5 6 7 3 4 1]


In [10]:
# b) Perform concatenation of two 2D arrays in row-by-row manner.
array_2d_1=np.array([[1, 2], [3, 4]])
array_2d_2=np.array([[5, 6], [7, 8]])
concatenated_array_2d=np.concatenate((array_2d_1, array_2d_2), axis=0)
print("Concatenated 2D Array (row-by-row): \n", concatenated_array_2d)

Concatenated 2D Array (row-by-row): 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
# c) Split the array [4, 5, 6, 3, 9] into 3 sub-arrays.
array_to_split_1d=np.array([4, 5, 6, 3, 9])
split_array_1d=np.array_split(array_to_split_1d, 3)
print("Split 1D Array into 3 sub-arrays: ", split_array_1d)

Split 1D Array into 3 sub-arrays:  [array([4, 5]), array([6, 3]), array([9])]


In [12]:
# d) Split the 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]] into 3 sub-arrays.
array_to_split_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
split_array_2d=np.array_split(array_to_split_2d, 3)
print("Split 2D Array into 3 sub-arrays: \n", split_array_2d)

Split 2D Array into 3 sub-arrays: 
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


## Question-4

In [13]:
# a) Given an array [1, 2, 3, 4, 5, 4, 4]. Find the index of element 4.
array_a=np.array([1, 2, 3, 4, 5, 4, 4])
indices_of_4=np.where(array_a==4)
print("Indices of element 4 in the array: ", indices_of_4[0])

Indices of element 4 in the array:  [3 5 6]


In [14]:
# b) Given a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]. Find the index of element 5.
array_b=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
index_of_5=np.argwhere(array_b==5)
print("Index of element 5 in the 2D array: ", index_of_5[0])

Index of element 5 in the 2D array:  [1 1]


In [15]:
# c) Given an array [1, 2, 3, 4, 5, 6, 7, 8], find out the indices of odd elements and even elements.
array_c=np.array([1, 2, 3, 4, 5, 6, 7, 8])
indices_of_odd=np.where(array_c % 2 != 0)
indices_of_even=np.where(array_c % 2 == 0)
print("Indices of odd elements: ", indices_of_odd[0])
print("Indices of even elements: ", indices_of_even[0])

Indices of odd elements:  [0 2 4 6]
Indices of even elements:  [1 3 5 7]


## Question-5

In [16]:
# a) Sort the elements of given 1D array [6, 5, 1, 2, 9, 10, 36, 7] in ascending and descending order.
array_d=np.array([6, 5, 1, 2, 9, 10, 36, 7])
sorted_ascending=np.sort(array_d)
sorted_descending=np.sort(array_d)[::-1]
print("Array sorted in ascending order: ", sorted_ascending)
print("Array sorted in descending order: ", sorted_descending)

Array sorted in ascending order:  [ 1  2  5  6  7  9 10 36]
Array sorted in descending order:  [36 10  9  7  6  5  2  1]


In [17]:
# b) Sort the elements of given 2D array [[5, 3, 7], [8, 10, 6], [40, -2, 7]] in ascending and descending order.
array_e=np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])
sorted_2d_ascending=np.sort(array_e, axis=None).reshape(array_e.shape)
sorted_2d_descending=np.sort(array_e, axis=None)[::-1].reshape(array_e.shape)
print("2D array sorted in ascending order: \n", sorted_2d_ascending)
print("2D array sorted in descending order: \n", sorted_2d_descending)

2D array sorted in ascending order: 
 [[-2  3  5]
 [ 6  7  7]
 [ 8 10 40]]
2D array sorted in descending order: 
 [[40 10  8]
 [ 7  7  6]
 [ 5  3 -2]]


## Question-6

In [18]:
# a) Generate a 1-D array containing 6 random integers from 0 to 20.
random_integers_1d=np.random.randint(0, 21, size=6)
print("1-D array with 6 random integers from 0 to 20: ", random_integers_1d)

1-D array with 6 random integers from 0 to 20:  [ 3 17 10 19 12  4]


In [19]:
# b) Generate a 1-D array containing 5 random floats.
random_floats_1d=np.random.random(size=5)
print("1-D array with 5 random floats: ", random_floats_1d)

1-D array with 5 random floats:  [0.82740425 0.00992098 0.58402567 0.63902303 0.78183292]


In [20]:
# c) Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 50.
random_integers_2d=np.random.randint(0, 51, size=(3, 5))
print("2-D array with 3 rows, each containing 5 random integers from 0 to 50: \n", random_integers_2d)

2-D array with 3 rows, each containing 5 random integers from 0 to 50:
 [[37 47 23 16 25]
 [48 23  4 16 13]
 [ 7  8  7 15 16]]


In [21]:
# d) Generate a 2-D array with 3 rows, each row containing 5 random numbers.
random_floats_2d=np.random.random(size=(3, 5))
print("2-D array with 3 rows, each containing 5 random numbers: \n", random_floats_2d)

2-D array with 3 rows, each containing 5 random numbers:
 [[0.2051029  0.66389233 0.83171903 0.81220833 0.66530171]
 [0.21750151 0.78387687 0.6674785  0.01624814 0.70263807]
 [0.02311226 0.9053633  0.24512777 0.19863136 0.78795234]]


In [22]:
# e) Given a 1-D array [6, 5, 1, 2, 9, 10, 36, 7]. Shuffle the elements of the array randomly.
array_f = np.array([6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(array_f)
print("Shuffled 1-D array: ", array_f)

Shuffled 1-D array:  [10  2  5  1  7  6  9 36]


In [23]:
# f) Shuffle the elements of the given 2-D array randomly.
array_to_shuffle_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
shuffled_array_2d=array_to_shuffle_2d.flatten()
np.random.shuffle(shuffled_array_2d)
shuffled_array_2d=shuffled_array_2d.reshape(array_to_shuffle_2d.shape)
print("2-D array after shuffling: \n", shuffled_array_2d)

2-D array after shuffling: 
 [[10  8  1]
 [ 5  3 11]
 [ 4 12  7]
 [ 9  6  2]]


# Part-B

## Question-1

In [30]:
import pandas as pd

# Read the dataset
wine_data=pd.read_csv('winequality_red.csv', sep=';')
wine_data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

## Question-2

In [36]:
# Convert the DataFrame to a NumPy array
wine_data_np=wine_data.to_numpy()
print(type(wine_data_np))

<class 'numpy.ndarray'>


## Question-3

In [37]:
# Check the shape of the NumPy array
print("Shape of wine_data_np: ", wine_data_np.shape)

Shape of wine_data_np:  (1599, 12)


## Question-4

In [38]:
# Slice the last column for Y
Y=wine_data_np[:, -1]
print("Shape of Y: ", Y.shape)

Shape of Y:  (1599,)


In [39]:
# Slice all columns except the last for X
X=wine_data_np[:, :-1]
print("Shape of X:", X.shape)

Shape of X: (1599, 11)


## Question-5

In [40]:
# Compute the mean for all columns in X
mean_X=np.mean(X, axis=0)
print("Mean for all columns in X: ", mean_X)

Mean for all columns in X:  [ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311]


In [41]:
from scipy import stats

# Compute the mode for the last column Y
mode_Y=stats.mode(Y)
print("Mode of Y: ", mode_Y.mode[0])

Mode of Y:  5.0


/var/folders/cc/z6s568k952l7_rtyfdvzhchm0000gn/T/ipykernel_7839/2272687886.py:4: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_Y=stats.mode(Y)


In [43]:
# Compute the standard deviation for all columns in X
std_X=np.std(X, axis=0)
print("Standard deviation for all columns in X: ", std_X)

Standard deviation for all columns in X:  [1.74055180e+00 1.79003704e-01 1.94740214e-01 1.40948711e+00
 4.70505826e-02 1.04568856e+01 3.28850367e+01 1.88674370e-03
 1.54338181e-01 1.69453967e-01 1.06533430e+00]
